# Generated by Django 5.1.6 on 2025-06-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название класса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Игровой класс',
                'verbose_name_plural': 'Игровые классы',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя игрока')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_tg_name', models.CharField(blank=True, default='none', max_length=35, null=True, verbose_name='Имя аккаунта в телеграмм')),
                ('user_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Телеграм игрок',
                'verbose_name_plural': 'Телеграм игроки',
            },
        ),
        migrations.CreateModel(
            name='PlayerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='bot.gameclass', verbose_name='Игровой класс')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_classes', to='bot.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Класс игрока',
                'verbose_name_plural': 'Классы игроков',
                'unique_together': {('player', 'game_class')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='selected_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_players', to='bot.playerclass', verbose_name='Выбранный класс'),
        ),
    ]
