# Generated by Django 5.1.6 on 2025-06-15 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название активности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание активности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to='bot.user', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bot.activity', verbose_name='Активность')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bot.player', verbose_name='Игрок')),
                ('player_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to='bot.playerclass', verbose_name='Класс игрока')),
            ],
            options={
                'verbose_name': 'Участник активности',
                'verbose_name_plural': 'Участники активности',
                'unique_together': {('activity', 'player')},
            },
        ),
    ]
