# Generated by Django 5.1.6 on 2025-06-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_activity_activityparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='base_coefficient',
            field=models.FloatField(default=1.0, verbose_name='Базовый коэффициент'),
        ),
        migrations.AddField(
            model_name='activity',
            name='class_coefficients',
            field=models.JSONField(default=dict, help_text='Словарь с коэффициентами для каждого класса в формате {"class_name": coefficient}', verbose_name='Коэффициенты для классов'),
        ),
        migrations.AddField(
            model_name='activity',
            name='level_coefficient',
            field=models.FloatField(default=0.1, help_text='Дополнительный коэффициент за каждый уровень персонажа', verbose_name='Коэффициент за уровень'),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='points_earned',
            field=models.FloatField(default=0, verbose_name='Заработанные баллы'),
        ),
    ]
