# Generated by Django 5.1.6 on 2025-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_activity_base_coefficient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='class_coefficients',
            field=models.JSONField(default=list, help_text='Список коэффициентов для каждого класса в порядке их создания', verbose_name='Коэффициенты для классов'),
        ),
    ]
