# Generated by Django 5.1.6 on 2025-06-16 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_activity_class_coefficients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='class_coefficients',
        ),
        migrations.CreateModel(
            name='ActivityClassCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(default=1.0, verbose_name='Коэффициент')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_coefficients', to='bot.activity', verbose_name='Активность')),
                ('game_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_coefficients', to='bot.gameclass', verbose_name='Игровой класс')),
            ],
            options={
                'verbose_name': 'Коэффициент класса активности',
                'verbose_name_plural': 'Коэффициенты классов активности',
                'unique_together': {('activity', 'game_class')},
            },
        ),
    ]
