# Generated by Django 5.1.6 on 2025-06-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_activity_class_coefficients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='level_bonus_base',
            field=models.FloatField(default=1.0, help_text='Базовый множитель для расчёта бонуса за уровень', verbose_name='Базовый бонус за уровень'),
        ),
    ]
